name: Prepare Release

on:
  workflow_dispatch:

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Prepare Release and Create Pull Request
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      run: ./gradlew createPullRequestRelease
