name: Build Release

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Generate Release State
      run: ./gradlew generateReleaseStateLastCommit
    - name: Gradle Build and Release
      env:
        AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      run: ./gradlew releaseAddOn
